-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2MbmWOZ2otGQE/fZ
5+VVHyxromnZJkgm1ZU1iN4cGAagCgYIKoZIzj0DAQehRANCAASrguQXIp/CPx47
TKXMg0a0LbcXaNSKnOeXk1pSOMrBa7pA578cxPDcxifLwL5VgmkSYusKvuXGSbEi
/nKHLlca
-----END PRIVATE KEY-----